cfg: ./models/custom_yolov5s.yaml
data: ./models/uc_data.yaml
hyp: ''
epochs: 300
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
weights: ./weights/yolov5s.pt
name: yolov5s_bdd_noprew
device: ''
multi_scale: false
single_cls: false
